labels:
  - name: Component:Backend
    color: "#dadada"
  - name: Component:iOS
    color: "#dadada"
  - name: Component:Android
    color: "#dadada"
  - name: Component:Web
    color: "#dadada"
  - name: Component:Desktop
    color: "#dadada"
  - name: Priority:p1-urgent
    color: "#ba1a1a"
    description: Urgent priority
  - name: Priority:p2-high
    color: "#ba1a1a"
    description: High priority
  - name: Priority:p3-medium
    description: Normal priority
    color: "#ba1a1a"
  - name: Priority:p4-low
    description: Low priority
    color: "#ba1a1a"
  - name: Type:Good-First-Issue
    color: "#e2baff"
  - name: Type:Story
    color: "#e2baff"
  - name: Type:Epic
    color: "#e2baff"
  - name: Type:Bug
    color: "#ff0000"
  - name: Type:Feature
    color: "#e2baff"
  - name: Type:Enhancement
    color: "#e2baff"
  - name: Type:Security
    color: "#e2baff"
  - name: Type:Breaking-Change
    color: "#e2baff"
  - name: Type:Dependencies
    color: "#e2baff"
  - name: Type:Design
    color: "#e2baff"
  - name: Type:Maintenance
    description: E.g. technical debt, packaging, etc.
    color: "#e2baff"
  - name: Type:Organizational
    color: "#e2baff"
  - name: Type:DevOps
    description: Related to CI/CD
    color: "#e2baff"
  - name: Type:Documentation
    color: "#e2baff"
  - name: Type:Test
    color: "#e2baff"
  - name: Type:Accessibility-Defect
    color: "#e2baff"
  - name: Status:Proposal
    color: "#20434f"
  - name: Status:Accepted
    color: "#20434f"
  - name: Status:Analysis
    color: "#20434f"
  - name: Status:Needs-Info
    color: "#20434f"
  - name: Status:In-Progress
    color: "#20434f"
  - name: Status:Needs-Review
    color: "#20434f"
  - name: Status:Tested
    color: "#20434f"
  - name: Status:Completed
    color: "#20434f"
  - name: Status:Blocked
    color: "#20434f"
  - name: Status:Duplicate
    color: "#20434f"
  - name: Status:Wont-Fix
    color: "#20434f"
